### ISSUE TITLE
admin form fieldset issue

### ISSUE THREAD

**Issue by WajahatKanju** [app-generator/django-admin-datta#4]
Code
```
@admin.register(Center)
class CenterAdmin(admin.ModelAdmin):
    fields = [("no", "title"), "address"]
```
Intended Behaviour  **Django Default** 
![intended](https://github.com/app-generator/django-admin-datta/assets/48358590/2305a567-6d1a-40fa-b198-176b5d2399c7)

Current Behaviour of app

![actual](https://github.com/app-generator/django-admin-datta/assets/48358590/4ed7f3b2-c660-4cc9-877c-6c5de644b5d5)

**Comment by WajahatKanju** [comment]
As mentioned in Django Docs  @ https://docs.djangoproject.com/en/4.2/ref/contrib/admin/
![docs](https://github.com/app-generator/django-admin-datta/assets/48358590/b6cb4039-3ae4-497c-bc2c-a6963e750a9f)

**Comment by WajahatKanju** [comment]
@app-generator @mominur-helios  @imran-helios . I am scratching my head to identify and resolve the issues. Once you have fixed the problem, could you kindly inform me via email and provide details about what was causing the issue? This will enable me to contribute through a pull request in the future. Thank you in advance.

**Comment by WajahatKanju** [comment]
@app-generator @mominur-helios  @imran-helios . I am scratching my head to identify and resolve the issues. Once you have fixed the problem, could you kindly inform me via email and provide details about what was causing the issue? This will enable me to contribute through a pull request in the future. Thank you in advance.

**Comment by app-generator** [comment]
Hello @WajahatKanju 

We will keep looking for a solution. Once the fix is done, we will update the status here. 

@mominur-helios please take a look. 

TY!

**Comment by app-generator** [comment]
Hello @WajahatKanju 

The fix is delivered in version `v1.0.10`.

Ty @mominur-helios for your work.

**Comment by WajahatKanju** [comment]
@mominur-helios thanks for fixing it. But can you please mail on how you fix it.

**Comment by ghost** [comment]
@WajahatKanju  check this commit, you will get it
https://github.com/app-generator/django-admin-datta/pull/6/commits/7e026511154d72b70b211f6a82f260f774b53287

**Comment by WajahatKanju** [comment]
@mominur-helios , one more thing: the default datepicker is much more user-friendly, with options to change the year and other features, compared to the one integrated into the app? Thank you.

I have changed it in my current App. but i don't want to change it in every other Django app that i build using your theme so Please Change it

Default: 

**- Easy to select year. 
- Change Month etc easily**

![Screenshot 2023-06-04 021727](https://github.com/app-generator/django-admin-datta/assets/48358590/27062a32-3591-4d6a-9c91-9e907beb2928)

Current: 

**- Frustrates The User**

![Screenshot 2023-06-04 021842](https://github.com/app-generator/django-admin-datta/assets/48358590/ba9a85ff-daa8-489d-9784-5de76c4770be)

**Comment by WajahatKanju** [comment]
I am just pointing it out. Change it if you want. Because i had to change it my users didn't like it
